apiVersion: v1
kind: Service
metadata:
  name: okjtxdy
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okjtxdy"
    port: 8080
  selector:
    app: okjtxdy
